### PR TITLE
Load book from URL (will only work on hosted server)

### PR DESCRIPTION
**Pull request by codedread**

### CODE REVIEW

**Comment by adamhathcock** [comment]
Any chance to get some functionality that will load a URL from a query string?

Something like: kthmoon.html?file=https://etc.com/test.cbr or even just a local path?

**Comment by codedread** [comment]
@adamhathcock yes, I plan to do this (in a future CL).  It's pretty straightforward and works better than what the IPFS guy did (using a hash).  I'll do that tonight.

And it's not Keith Moon... it's kthoom :D

**Comment by adamhathcock** [comment]
Haha oops.  I was using a phone at the time so please forgive.

**Comment by codedread** [comment]
Loading from the URL is now supported.  See the README:

.../kthoom/?bookUri=/my/awesome/book.cbz

**Pull request merged**
