### PR TITLE
Add Long-strip view and hide button

### PR DESCRIPTION
**Pull request by ProgramComputer**
evt.preventhandler() was commented too.

### CODE REVIEW

**Comment by codedread** [comment]
Long-strip mode is a cool idea - rthanks for sending this my way!

I patched it and tried it out and came across a few problems though:

1) '3' doesn't seem to switch me into the new mode as advertised, only the menu.

2) It doesn't work in rotated mode (anything not zero degrees). Full-screen and rotated left 90 degrees is how I most often read comic books on my laptop (https://photos.app.goo.gl/AS5NpXG3bRHYvmuo8), so before I integrate this feature I would want some solution there. Maybe it wouldn't be too hard to implement... still scroll pages in top-to-bottom in the web page. If you're rotated left, pages are in reverse order and user is positioned at the first page at the _bottom_ of the scroll pane (they scroll "up" to advance pages). If you're rotated right, pages are in natural order and user is positioned at the first page at the top of the scroll page (they scroll "down" to advance pages).

3) Long-strip view always seems to have "Fit to width" mode. Is this intentional? It seems natural in non-rotated mode, but if I'm in 90/270 degree rotation, it feels like fit-height is more natural.

**Comment by codedread** [comment]
4) I can switch into Long-strip view before the book is even loaded. This leads to a confusing state until pages finish loading - maybe prevent this somehow until then?

**Comment by ProgramComputer** [comment]
@codedread 
The 3 key should be functional now.

Long-strip fit to width was originally the intention for all rotations. The Fit to Height's width is the natural width which may differ by image.

Showing before the book is fully loaded is fixed.
Currently, the long strip is top-to-bottom orientation for both rotations not left-to-right or right-to-left. This addition would be long-strip side-to-to side but this merge will address top-to-bottom.

**Comment by codedread** [comment]
I added all your changes to a new branch and tried to fix some of it. It's getting closer here: https://github.com/codedread/kthoom/tree/long-strip-view

But I'd like to think about it some more and try to fix the rotated and different fit-mode cases. In addition I think we are overdue for some unit tests here too...

**Comment by codedread** [comment]
I merged and tweaked the "Hide panel buttons" functionality into the master branch.
Since all rest of the changes are not he long-strip-view branch, I think we can close this pull request and continue development there.

**Pull request closed without merging**
